### PR TITLE
Read and merge properties from multiple properties files

### PR DESCRIPTION
**Pull request by jburwell**
- Reads and merges properties from multiple files.  The first file provided is required, and all subsequent files are treated as optional where property values from subsequent files override those in preceding files.
- Adds unit tests for the multiple file behavior
- Adds description of multiple file behavior to README.md
- Fixes a pre-existing jshint warnings
- Adds vim swap files to the .gitignore

### CODE REVIEW

**Comment by slawrence** [comment]
Looks good! Thanks!

**Comment by jburwell** [comment]
@slawrence when do expect to cut a release that includes this PR?

**Comment by slawrence** [comment]
v0.1.2 should have this unless I flubbed the publish to npm.

**Comment by jburwell** [comment]
@slawrence awesome.  Thank you very much for getting merged and released so quickly.

**Pull request merged**
